version: "3.8"


services:
  api:
      build: .
      container_name: test
      environment:
          API_KEY_RANDOM: ""
      ports:
        - "8080:8080"
      networks:
        - default
      volumes:
      - .:/app/